services:
  auth_service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "50051:50051"
      - "9000:9000"
    networks:
      - auth_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8000"
      - "1993:1993"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - auth_service
    networks:
      - auth_net

networks:
  auth_net:








